// 本文件由 scripts/build-icons.mjs 自动生成，请勿手改
/* eslint-disable */

export const GLYPH: Record<string, string> = {
    'arrow-left': '\uf13d',
    'arrow-up': '\uf13c',
    'bag': '\uf13b',
    'bar-chart': '\uf13a',
    'book': '\uf137',
    'book-lines': '\uf139',
    'book-open': '\uf138',
    'bookmark': '\uf135',
    'bookmark-fill': '\uf136',
    'brand-apple': '\uf134',
    'brand-phone': '\uf133',
    'brand-weixin': '\uf132',
    'check': '\uf131',
    'chevron-down': '\uf130',
    'chevron-left': '\uf12f',
    'chevron-right': '\uf12e',
    'chevron-up': '\uf12d',
    'clipboard': '\uf12c',
    'clock': '\uf12b',
    'cloud': '\uf12a',
    'concentric': '\uf129',
    'edit': '\uf128',
    'external': '\uf127',
    'eye': '\uf125',
    'eye-off': '\uf126',
    'file-lines': '\uf124',
    'filter': '\uf123',
    'flask': '\uf122',
    'focus': '\uf121',
    'gem': '\uf120',
    'globe': '\uf11f',
    'heart': '\uf11d',
    'heart-fill': '\uf11e',
    'info': '\uf11c',
    'layout': '\uf11b',
    'log-in': '\uf11a',
    'more-vertical': '\uf119',
    'move': '\uf118',
    'package': '\uf117',
    'plus': '\uf116',
    'refresh-ccw': '\uf115',
    'search': '\uf114',
    'settings': '\uf113',
    'shield': '\uf112',
    'shopping-bag': '\uf111',
    'sliders': '\uf110',
    'sparkle': '\uf10f',
    'star': '\uf10d',
    'star-fill': '\uf10e',
    'tab-book': '\uf10c',
    'tab-folder': '\uf10b',
    'tab-grid': '\uf10a',
    'tab-person': '\uf109',
    'target': '\uf108',
    'trash': '\uf107',
    'user': '\uf106',
    'users': '\uf105',
    'x': '\uf104',
    'zap': '\uf101',
    'zap-2': '\uf103',
    'zap-bolt': '\uf102',
};

/** 取图标字形（找不到返回空串） */
export function glyph(name: string): string {
    return GLYPH[name] ?? '';
}
